name: Generate Flash USDT SEO Pages

on:
  workflow_dispatch:
    inputs:
      method:
        description: 'API call method (python/js/curl)'
        required: true
        default: 'python'

jobs:
  generate-html:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Enable dependency caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install together python-dotenv pathlib

      - name: Generate content
        run: python .github/scripts/generate.py
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated/
          if git diff --quiet --cached; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated Flash USDT pages [skip ci]"
            git push
          fi
