name: Generate Flash USDT SEO Pages

on:
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest
    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest checkout version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Enable caching for faster installs

      - name: Install dependencies
        run: pip install requests

      - name: Run HTML Generator
        run: |
          python .github/scripts/generate.py || exit 1
          # Verify files were generated
          if [ ! -f generated/index.html ]; then
            echo "❌ Error: No files generated!"
            exit 1
          fi

      - name: Commit and Push
        run: |
          # Only commit if there are changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add generated/ index.html  # Specific files only
          
          if ! git diff --quiet --staged; then
            git commit -m "Generated Flash USDT HTML via AI [$(date +%Y-%m-%d)]"
            git push
          else
            echo "No changes to commit"
          fi
