name: Generate and Deploy Flash USDT SEO Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment (dev/prod)'
        required: true
        default: 'dev'

jobs:
  generate-content:
    runs-on: ubuntu-latest
    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Generate HTML Content
        run: |
          python .github/scripts/generate.py \
            --env ${{ inputs.environment }} \
            --output-dir generated
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}

      - name: Generate Sitemap
        run: python .github/scripts/sitemap.py

  deploy:
    needs: generate-content
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}
    
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated

  post-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ always() }}
    
    steps:
      - name: Notify Search Engines
        run: |
          python .github/scripts/ping_search_console.py
