name: Generate Flash USDT SEO Pages

on:
  workflow_dispatch:
    inputs:
      method:
        description: 'API call method (curl/python/js)'
        required: true
        default: 'python'

jobs:
  generate-html:
    runs-on: ubuntu-latest
    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install together python-dotenv

      - name: Run generation script
        run: python .github/scripts/generate.py
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API }}

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "Auto-generated Flash USDT pages"
            git push
          fi
